version: "3.9"

services:
  db:
    image: postgres:16
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pg_data: